version: '3.7'
services:
  mongodb_container:
    container_name: ${ENV}
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: